server.port: 9000

spring:
  application.name: service1
  sleuth.sampler.percentage: 1.0
  zipkin:
      locator.discovery.enabled: true
      baseUrl: http://zipkin-server/

logging:
  file: serviceOne.log
  level:
    org.springframework.cloud.sleuth: DEBUG